name: marvelous
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.4
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  line_icons: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: AvengeroDisassembled
      fonts:
        - asset: fonts/AvengeroDisassembled-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-SemiBold.ttf
    - family: Marvel
      fonts:
        - asset: fonts/Marvel-Regular.ttf
    - family: SyneTactile
      fonts:
        - asset: fonts/SyneTactile-Regular.ttf
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf
    - family: ShadowsIntoLight
      fonts:
        - asset: fonts/ShadowsIntoLight-Regular.ttf



